/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2020-04-16 01:07:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/member/picture_js.jsp", Long.valueOf(1586933385901L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<body>\r\n");
      out.write("<!-- Content Wrapper. Contains page content -->\r\n");
      out.write(" <div class=\"content-wrapper\">\r\n");
      out.write("\t<!-- Content Header (Page header) -->\r\n");
      out.write("\t  <section class=\"content-header\">\r\n");
      out.write("\t  \t<div class=\"container-fluid\">\r\n");
      out.write("\t  \t\t<div class=\"row md-2\">\r\n");
      out.write("\t  \t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t  \t\t\t\t<h1>회원등록</h1>\r\n");
      out.write("\t  \t\t\t</div>\r\n");
      out.write("\t  \t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t  \t\t\t\t<ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("\t\t\t\t        <li class=\"breadcrumb-item\">\r\n");
      out.write("\t\t\t\t        \t<a href=\"lis\">\r\n");
      out.write("\t\t\t\t\t        \t<i class=\"fa fa-dashboard\"></i> 회원관리\r\n");
      out.write("\t\t\t\t\t        </a>\r\n");
      out.write("\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t        <li class=\"breadcrumb-item active\">\r\n");
      out.write("\t\t\t\t        \t등록\r\n");
      out.write("\t\t\t\t        </li>\t\t        \r\n");
      out.write("   \t  \t\t\t\t</ol>\r\n");
      out.write(" \t\t\t\t</div>\r\n");
      out.write(" \t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Main content -->\r\n");
      out.write("\t<section class=\"content register-page\" style=\"height: 586.391px; \">\r\n");
      out.write("\t\t<div class=\"register-box\">\r\n");
      out.write("\t\t\t<!-- form start -->\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"register-card-body\">\r\n");
      out.write("\t\t\t\t\t<form role=\"form\" class=\"form-horizontal\" action=\"regist\" method=\"post\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"picture\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mailbox-attachments clearfix\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mailbox-attachment-icon has-img\" id=\"pictureView\" style=\"border: 1px solid green; height: 200px; width: 140px; margin: 0 auto;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group input-group-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"inputFile\" class=\" btn btn-warning btn-sm btn-flat input-group-addon\">파일선택</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"inputFileName\" class=\"form-control\" type=\"text\" name=\"picture\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-append-sm\">\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info btn-sm btn-append\" onclick=\"upload_go();\">업로드</button>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t  </div>\t\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t <label for=\"id\" class=\"col-sm-3\" style=\"font-size:0.9em;\" >\r\n");
      out.write("\t\t\t\t\t\t\t \t<span style=\"color:red;font-weight:bold;\">*</span>아이디</label>\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9 input-group input-group-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"id\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"this.value=this.value.replace(/[\\ㄱ-ㅎㅏ-ㅣ가-힣]/g, &#39;&#39;);\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"id\" placeholder=\"13글자 영문자,숫자 조합\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-append-sm\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" onclick=\"idCheck_go();\"  class=\"btn btn-info btn-sm btn-append\">중복확인</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"pwd\" class=\"col-sm-3\" style=\"font-size:0.9em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:red;font-weight:bold;\">*</span>패스워드</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9 input-group-sm\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"pwd\" type=\"password\" class=\"form-control\" id=\"pwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"20글자 영문자,숫자,특수문자 조합\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"name\" class=\"col-sm-3\" style=\"font-size:0.9em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:red;font-weight:bold;\">*</span>이&nbsp;&nbsp;름</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9 input-group-sm\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"name\" type=\"text\" class=\"form-control\" id=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"이름을 입력하세요.\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"authority\" class=\"col-sm-3 control-label text-center\" >권 한</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"authority\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"ROLE_USER\">사용자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"ROLE_MANAGER\">운영자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"ROLE_ADMIN\">관리자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"email\" class=\"col-sm-3\" style=\"font-size:0.9em;\">이메일</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9 input-group-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"email\" type=\"email\" class=\"form-control\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"example@naver.com\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"phone\" class=\"col-sm-3 control-label\">전화번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-9\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select style=\"width:75px;\" name=\"phone\" id=\"phone\" class=\"form-control float-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">-선택-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"float-left\" style=\"padding: 0; text-align: center;\">&nbsp;-&nbsp;</label>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input style=\"width:68px;\" name=\"phone\" type=\"text\" class=\"form-control float-left\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"float-left\" style=\"padding: 0; text-align: center;\">&nbsp;-</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input style=\"width:68px;\" name=\"phone\" type=\"text\" class=\"form-control float-right\" />\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- js의 function을 호출할때 꼭 파라미터로 넘겨줄것!!! (js에서는 el문 못씀) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-info\" onclick=\"SubmitMemberRegist('form');\">가입하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t\t\t \t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"cancelBtn\" onclick=\"CloseWindow();\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-default float-right\">&nbsp;&nbsp;&nbsp;취 &nbsp;&nbsp;소&nbsp;&nbsp;&nbsp;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div><!-- register-card-body -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\t\t<!-- /.content -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form role=\"imageForm\" action=\"upload/picture\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<input id=\"inputFile\" name=\"pictureFile\" type=\"file\" class=\"form-control\" style=\"display:none;\">\r\n");
      out.write("\t<input id=\"oldFile\" type=\"hidden\" name=\"oldPicture\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" name=\"checkUpload\" value=\"0\" />\t\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$('input#inputFile').on('change', function(event){\r\n");
      out.write("\t\t$('input[name=\"checkUpload\"]').val(0);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\tvar fileFormat = this.value.substr(this.value.lastIndexOf(\".\")+1).toUpperCase();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\tif(fileFormat!=\"JPG\" && fileFormat!=\"PNG\"){\r\n");
      out.write("\t\t\talert(\"이미지는 jpg 형식만 가능합니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\tif(this.files[0].size>1024*1024*1){\r\n");
      out.write("\t\t\talert(\"사진 용량은 1MB 이하만 가능합니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//files[0] : 파일 정보가 여러가지 저장되는데 그 중 경로는 첫번째 인덱스에 존재한다.\r\n");
      out.write("\t\tdocument.getElementById('inputFileName').value = this.files[0].name;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//자바 스크립트의 if문 : 데이터가 있으면 true, 없으면 false\r\n");
      out.write("\t\tif(this.files && this.files[0]){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//FileReader() : 브라우저에 존재하는 객체\r\n");
      out.write("\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//이벤트\r\n");
      out.write("\t\t\treader.onload = function(e){\r\n");
      out.write("\t\t\t\t//이미지 미리보기\r\n");
      out.write("\t\t\t\t//e.target.result : event 객체에 있는 target의 result\r\n");
      out.write("\t\t\t\t//'background-size' : 'cover' <-> 'contain'\r\n");
      out.write("\t\t\t\t$('div#pictureView').css({\r\n");
      out.write("\t\t\t\t\t'background-image' : 'url(' + e.target.result + ')',\r\n");
      out.write("\t\t\t\t\t'background-position' : 'center',\r\n");
      out.write("\t\t\t\t\t'background-size' : 'cover',\r\n");
      out.write("\t\t\t\t\t'background-repeat' : 'no-repeat'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//이거 안 쓰면 파일 이름 이상하게 나옴\r\n");
      out.write("\t\t\treader.readAsDataURL(this.files[0]);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction upload_go(){\r\n");
      out.write("\t\t//form 태그 양식을 객체화\r\n");
      out.write("\t\tvar form = new FormData($('form[role=\"imageForm\"]')[0]); //[0]번으로 지정 안하면 htmlElement가 아니라 object로 꺼내옴\r\n");
      out.write("\t\t//$('form[name=\"frm\"]').submit(); 같은 경우는 submit 메서드가 저절로 0번째를 찾아서 submit하기 때문에 [0] 안씀\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($('input[name=\"[pictureFile]\"]').val() == \"\"){\r\n");
      out.write("\t\t\talert(\"사진을 선택하세요.\");\r\n");
      out.write("\t\t\t$('input[name=\"pictureFile\"]').click();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//processData : false, contentType : false -> form 객체를 보낼때 꼭 해줘야함. form객체에 이미 내장되어있음\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.print( request. getContextPath() );
      out.write("/member/picture\",\r\n");
      out.write("\t\t\tdata : form,\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tprocessData : false,\r\n");
      out.write("\t\t\tcontentType : false,\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t$('input#oldFile').val(data);\r\n");
      out.write("\t\t\t\t$('form[role=\"form\"] > input[name=\"picture\"]').val(data);\r\n");
      out.write("\t\t\t\t$('input[name=\"checkUpload\"]').val(1);\r\n");
      out.write("\t\t\t\talert(\"사진을 업로드 했습니다.\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr, exception){\r\n");
      out.write("\t\t\t\talert(\"파일 업로드를 실패했습니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
