/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-02 00:37:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("This is a starter template page. Use this page to start your new project from\r\n");
      out.write("scratch. This page gets rid of all links and provides the needed markup only.\r\n");
      out.write("-->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("  <title>AdminLTE 3 | Starter</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/css/adminlte.min.css\">\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar -->\r\n");
      out.write("  <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <!-- Left navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"index3.html\" class=\"nav-link\">Home</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- SEARCH FORM -->\r\n");
      out.write("    <form class=\"form-inline ml-3\">\r\n");
      out.write("      <div class=\"input-group input-group-sm\">\r\n");
      out.write("        <input class=\"form-control form-control-navbar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <div class=\"input-group-append\">\r\n");
      out.write("          <button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("            <i class=\"fas fa-search\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- Messages Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-comments\"></i>\r\n");
      out.write("          <span class=\"badge badge-danger navbar-badge\">3</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/img/user1-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 mr-3 img-circle\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Brad Diesel\r\n");
      out.write("                  <span class=\"float-right text-sm text-danger\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">Call me whenever you can...</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/img/user8-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  John Pierce\r\n");
      out.write("                  <span class=\"float-right text-sm text-muted\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">I got your message bro</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/img/user3-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Nora Silvester\r\n");
      out.write("                  <span class=\"float-right text-sm text-warning\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">The subject goes here</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Messages</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- Notifications Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-bell\"></i>\r\n");
      out.write("          <span class=\"badge badge-warning navbar-badge\">15</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <span class=\"dropdown-header\">15 Notifications</span>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-envelope mr-2\"></i> 4 new messages\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">3 mins</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-users mr-2\"></i> 8 friend requests\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">12 hours</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-file mr-2\"></i> 3 new reports\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">2 days</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Notifications</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"control-sidebar\" data-slide=\"true\" href=\"#\"><i\r\n");
      out.write("            class=\"fas fa-th-large\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- /.navbar -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Sidebar Container -->\r\n");
      out.write("  <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("    <!-- Brand Logo -->\r\n");
      out.write("    <a href=\"index3.html\" class=\"brand-link\">\r\n");
      out.write("      <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\"\r\n");
      out.write("           style=\"opacity: .8\">\r\n");
      out.write("      <span class=\"brand-text font-weight-light\">AdminLTE 3</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("      <!-- Sidebar user panel (optional) -->\r\n");
      out.write("      <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("        <div class=\"image\">\r\n");
      out.write("          <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/img/user2-160x160.jpg\" class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("          <a href=\"#\" class=\"d-block\">Alexander Pierce</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Menu -->\r\n");
      out.write("      <nav class=\"mt-2\">\r\n");
      out.write("        <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("          <!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library -->\r\n");
      out.write("          <li class=\"nav-item has-treeview menu-open\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-link active\">\r\n");
      out.write("              <i class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Starter Pages\r\n");
      out.write("                <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"nav nav-treeview\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link active\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Active Page</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                  <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                  <p>Inactive Page</p>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("              <i class=\"nav-icon fas fa-th\"></i>\r\n");
      out.write("              <p>\r\n");
      out.write("                Simple Link\r\n");
      out.write("                <span class=\"right badge badge-danger\">New</span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- /.sidebar-menu -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.sidebar -->\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <div class=\"content-header\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row mb-2\">\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <h1 class=\"m-0 text-dark\">Starter Page</h1>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\">Starter Page</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content-header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        \r\n");
      out.write("       \t<div class=\"row\">\r\n");
      out.write("       \t\t<div class=\"col-sm-6\">\r\n");
      out.write("       \t\t\t<div class=\"small-box bg-info\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h3>150</h3>\r\n");
      out.write("\r\n");
      out.write("                <p>New Orders</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"icon\">\r\n");
      out.write("                <i class=\"ion ion-bag\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              \t<a href=\"#\" class=\"small-box-footer\">More info <i class=\"fas fa-arrow-circle-right\"></i></a>\r\n");
      out.write("\t         </div>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t\t<div class=\"col-sm-6\">\r\n");
      out.write("       \t\t\t<div class=\"small-box bg-warning\">\r\n");
      out.write("              <div class=\"inner\">\r\n");
      out.write("                <h3>44</h3>\r\n");
      out.write("\r\n");
      out.write("                <p>User Registrations</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"icon\">\r\n");
      out.write("                <i class=\"ion ion-person-add\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("              <a href=\"#\" class=\"small-box-footer\">More info <i class=\"fas fa-arrow-circle-right\"></i></a>\r\n");
      out.write("             </div>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t</div><!-- .row -->\r\n");
      out.write("       \t\r\n");
      out.write("       \t<div class=\"row\">\r\n");
      out.write("       \t\t<div class=\"col-sm-4\">\r\n");
      out.write("       \t\t\t<div class=\"card card-primary\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h3 class=\"card-title\">Primary Outline</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-tools\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-tool\" data-card-widget=\"collapse\"><i class=\"fas fa-minus\"></i>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.card-tools -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-header -->\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                The body of the card\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-body -->\r\n");
      out.write("             </div>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t\t<div class=\"col-sm-4\">\r\n");
      out.write("       \t\t\t<div class=\"card card-success\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h3 class=\"card-title\">Success Outline</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-tools\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-tool\" data-card-widget=\"remove\"><i class=\"fas fa-times\"></i>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.card-tools -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-header -->\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                The body of the card\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-body -->\r\n");
      out.write("             </div>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t\t<div class=\"col-sm-4\">\r\n");
      out.write("       \t\t\t<div class=\"card card-warning\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h3 class=\"card-title\">Warning Outline</h3>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-tools\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-tool\" data-card-widget=\"collapse\"><i class=\"fas fa-minus\"></i>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.card-tools -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-header -->\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                The body of the card\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-body -->\r\n");
      out.write("             </div>\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t</div><!-- .row -->\r\n");
      out.write("       \t\r\n");
      out.write("       \t<div class=\"row\">\r\n");
      out.write("       \t\t<div class=\"col-sm-8\">\r\n");
      out.write("       \t\t\t<div class=\"card card-primary card-outline\">\r\n");
      out.write("\t            <div class=\"card-header\">\r\n");
      out.write("\t              <h3 class=\"card-title\">Read Mail</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t              <div class=\"card-tools\">\r\n");
      out.write("\t                <a href=\"#\" class=\"btn btn-tool\" data-toggle=\"tooltip\" title=\"Previous\"><i class=\"fas fa-chevron-left\"></i></a>\r\n");
      out.write("\t                <a href=\"#\" class=\"btn btn-tool\" data-toggle=\"tooltip\" title=\"Next\"><i class=\"fas fa-chevron-right\"></i></a>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-header -->\r\n");
      out.write("\t            <div class=\"card-body p-0\">\r\n");
      out.write("\t              <div class=\"mailbox-read-info\">\r\n");
      out.write("\t                <h5>Message Subject Is Placed Here</h5>\r\n");
      out.write("\t                <h6>From: support@adminlte.io\r\n");
      out.write("\t                  <span class=\"mailbox-read-time float-right\">15 Feb. 2015 11:03 PM</span></h6>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- /.mailbox-read-info -->\r\n");
      out.write("\t              <div class=\"mailbox-controls with-border text-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" data-container=\"body\" title=\"Delete\">\r\n");
      out.write("\t                    <i class=\"far fa-trash-alt\"></i></button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" data-container=\"body\" title=\"Reply\">\r\n");
      out.write("\t                    <i class=\"fas fa-reply\"></i></button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" data-container=\"body\" title=\"Forward\">\r\n");
      out.write("\t                    <i class=\"fas fa-share\"></i></button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <!-- /.btn-group -->\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" title=\"Print\">\r\n");
      out.write("\t                  <i class=\"fas fa-print\"></i></button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- /.mailbox-controls -->\r\n");
      out.write("\t              <div class=\"mailbox-read-message\">\r\n");
      out.write("\t                <p>Hello John,</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Keffiyeh blog actually fashion axe vegan, irony biodiesel. Cold-pressed hoodie chillwave put a bird\r\n");
      out.write("\t                  on it aesthetic, bitters brunch meggings vegan iPhone. Dreamcatcher vegan scenester mlkshk. Ethical\r\n");
      out.write("\t                  master cleanse Bushwick, occupy Thundercats banjo cliche ennui farm-to-table mlkshk fanny pack\r\n");
      out.write("\t                  gluten-free. Marfa butcher vegan quinoa, bicycle rights disrupt tofu scenester chillwave 3 wolf moon\r\n");
      out.write("\t                  asymmetrical taxidermy pour-over. Quinoa tote bag fashion axe, Godard disrupt migas church-key tofu\r\n");
      out.write("\t                  blog locavore. Thundercats cronut polaroid Neutra tousled, meh food truck selfies narwhal American\r\n");
      out.write("\t                  Apparel.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Raw denim McSweeney's bicycle rights, iPhone trust fund quinoa Neutra VHS kale chips vegan PBR&amp;B\r\n");
      out.write("\t                  literally Thundercats +1. Forage tilde four dollar toast, banjo health goth paleo butcher. Four dollar\r\n");
      out.write("\t                  toast Brooklyn pour-over American Apparel sustainable, lumbersexual listicle gluten-free health goth\r\n");
      out.write("\t                  umami hoodie. Synth Echo Park bicycle rights DIY farm-to-table, retro kogi sriracha dreamcatcher PBR&amp;B\r\n");
      out.write("\t                  flannel hashtag irony Wes Anderson. Lumbersexual Williamsburg Helvetica next level. Cold-pressed\r\n");
      out.write("\t                  slow-carb pop-up normcore Thundercats Portland, cardigan literally meditation lumbersexual crucifix.\r\n");
      out.write("\t                  Wayfarers raw denim paleo Bushwick, keytar Helvetica scenester keffiyeh 8-bit irony mumblecore\r\n");
      out.write("\t                  whatever viral Truffaut.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Post-ironic shabby chic VHS, Marfa keytar flannel lomo try-hard keffiyeh cray. Actually fap fanny\r\n");
      out.write("\t                  pack yr artisan trust fund. High Life dreamcatcher church-key gentrify. Tumblr stumptown four dollar\r\n");
      out.write("\t                  toast vinyl, cold-pressed try-hard blog authentic keffiyeh Helvetica lo-fi tilde Intelligentsia. Lomo\r\n");
      out.write("\t                  locavore salvia bespoke, twee fixie paleo cliche brunch Schlitz blog McSweeney's messenger bag swag\r\n");
      out.write("\t                  slow-carb. Odd Future photo booth pork belly, you probably haven't heard of them actually tofu ennui\r\n");
      out.write("\t                  keffiyeh lo-fi Truffaut health goth. Narwhal sustainable retro disrupt.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Skateboard artisan letterpress before they sold out High Life messenger bag. Bitters chambray\r\n");
      out.write("\t                  leggings listicle, drinking vinegar chillwave synth. Fanny pack hoodie American Apparel twee. American\r\n");
      out.write("\t                  Apparel PBR listicle, salvia aesthetic occupy sustainable Neutra kogi. Organic synth Tumblr viral\r\n");
      out.write("\t                  plaid, shabby chic single-origin coffee Etsy 3 wolf moon slow-carb Schlitz roof party tousled squid\r\n");
      out.write("\t                  vinyl. Readymade next level literally trust fund. Distillery master cleanse migas, Vice sriracha\r\n");
      out.write("\t                  flannel chambray chia cronut.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Thanks,<br>Jane</p>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- /.mailbox-read-message -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-body -->\r\n");
      out.write("\t            <div class=\"card-footer bg-white\">\r\n");
      out.write("\t              <ul class=\"mailbox-attachments d-flex align-items-stretch clearfix\">\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon\"><i class=\"far fa-file-pdf\"></i></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-paperclip\"></i> Sep2014-report.pdf</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>1,245 KB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon\"><i class=\"far fa-file-word\"></i></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-paperclip\"></i> App Description.docx</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>1,245 KB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon has-img\"><img src=\"../../dist/img/photo1.png\" alt=\"Attachment\"></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-camera\"></i> photo1.png</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>2.67 MB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon has-img\"><img src=\"../../dist/img/photo2.png\" alt=\"Attachment\"></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-camera\"></i> photo2.png</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>1.9 MB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t              </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-footer -->\r\n");
      out.write("\t            <div class=\"card-footer\">\r\n");
      out.write("\t              <div class=\"float-right\">\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-default\"><i class=\"fas fa-reply\"></i> Reply</button>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-default\"><i class=\"fas fa-share\"></i> Forward</button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-default\"><i class=\"far fa-trash-alt\"></i> Delete</button>\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-default\"><i class=\"fas fa-print\"></i> Print</button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("            <!-- /.card-footer -->\r\n");
      out.write("           </div>\r\n");
      out.write("       \t </div>\r\n");
      out.write("       \t \r\n");
      out.write("       \t <div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"card card-primary card-outline\">\r\n");
      out.write("\t            <div class=\"card-header\">\r\n");
      out.write("\t              <h3 class=\"card-title\">Read Mail</h3>\r\n");
      out.write("\t\r\n");
      out.write("\t              <div class=\"card-tools\">\r\n");
      out.write("\t                <a href=\"#\" class=\"btn btn-tool\" data-toggle=\"tooltip\" title=\"Previous\"><i class=\"fas fa-chevron-left\"></i></a>\r\n");
      out.write("\t                <a href=\"#\" class=\"btn btn-tool\" data-toggle=\"tooltip\" title=\"Next\"><i class=\"fas fa-chevron-right\"></i></a>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-header -->\r\n");
      out.write("\t            <div class=\"card-body p-0\">\r\n");
      out.write("\t              <div class=\"mailbox-read-info\">\r\n");
      out.write("\t                <h5>Message Subject Is Placed Here</h5>\r\n");
      out.write("\t                <h6>From: support@adminlte.io\r\n");
      out.write("\t                  <span class=\"mailbox-read-time float-right\">15 Feb. 2015 11:03 PM</span></h6>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- /.mailbox-read-info -->\r\n");
      out.write("\t              <div class=\"mailbox-controls with-border text-center\">\r\n");
      out.write("\t                <div class=\"btn-group\">\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" data-container=\"body\" title=\"Delete\">\r\n");
      out.write("\t                    <i class=\"far fa-trash-alt\"></i></button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" data-container=\"body\" title=\"Reply\">\r\n");
      out.write("\t                    <i class=\"fas fa-reply\"></i></button>\r\n");
      out.write("\t                  <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" data-container=\"body\" title=\"Forward\">\r\n");
      out.write("\t                    <i class=\"fas fa-share\"></i></button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <!-- /.btn-group -->\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-default btn-sm\" data-toggle=\"tooltip\" title=\"Print\">\r\n");
      out.write("\t                  <i class=\"fas fa-print\"></i></button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- /.mailbox-controls -->\r\n");
      out.write("\t              <div class=\"mailbox-read-message\">\r\n");
      out.write("\t                <p>Hello John,</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Keffiyeh blog actually fashion axe vegan, irony biodiesel. Cold-pressed hoodie chillwave put a bird\r\n");
      out.write("\t                  on it aesthetic, bitters brunch meggings vegan iPhone. Dreamcatcher vegan scenester mlkshk. Ethical\r\n");
      out.write("\t                  master cleanse Bushwick, occupy Thundercats banjo cliche ennui farm-to-table mlkshk fanny pack\r\n");
      out.write("\t                  gluten-free. Marfa butcher vegan quinoa, bicycle rights disrupt tofu scenester chillwave 3 wolf moon\r\n");
      out.write("\t                  asymmetrical taxidermy pour-over. Quinoa tote bag fashion axe, Godard disrupt migas church-key tofu\r\n");
      out.write("\t                  blog locavore. Thundercats cronut polaroid Neutra tousled, meh food truck selfies narwhal American\r\n");
      out.write("\t                  Apparel.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Raw denim McSweeney's bicycle rights, iPhone trust fund quinoa Neutra VHS kale chips vegan PBR&amp;B\r\n");
      out.write("\t                  literally Thundercats +1. Forage tilde four dollar toast, banjo health goth paleo butcher. Four dollar\r\n");
      out.write("\t                  toast Brooklyn pour-over American Apparel sustainable, lumbersexual listicle gluten-free health goth\r\n");
      out.write("\t                  umami hoodie. Synth Echo Park bicycle rights DIY farm-to-table, retro kogi sriracha dreamcatcher PBR&amp;B\r\n");
      out.write("\t                  flannel hashtag irony Wes Anderson. Lumbersexual Williamsburg Helvetica next level. Cold-pressed\r\n");
      out.write("\t                  slow-carb pop-up normcore Thundercats Portland, cardigan literally meditation lumbersexual crucifix.\r\n");
      out.write("\t                  Wayfarers raw denim paleo Bushwick, keytar Helvetica scenester keffiyeh 8-bit irony mumblecore\r\n");
      out.write("\t                  whatever viral Truffaut.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Post-ironic shabby chic VHS, Marfa keytar flannel lomo try-hard keffiyeh cray. Actually fap fanny\r\n");
      out.write("\t                  pack yr artisan trust fund. High Life dreamcatcher church-key gentrify. Tumblr stumptown four dollar\r\n");
      out.write("\t                  toast vinyl, cold-pressed try-hard blog authentic keffiyeh Helvetica lo-fi tilde Intelligentsia. Lomo\r\n");
      out.write("\t                  locavore salvia bespoke, twee fixie paleo cliche brunch Schlitz blog McSweeney's messenger bag swag\r\n");
      out.write("\t                  slow-carb. Odd Future photo booth pork belly, you probably haven't heard of them actually tofu ennui\r\n");
      out.write("\t                  keffiyeh lo-fi Truffaut health goth. Narwhal sustainable retro disrupt.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Skateboard artisan letterpress before they sold out High Life messenger bag. Bitters chambray\r\n");
      out.write("\t                  leggings listicle, drinking vinegar chillwave synth. Fanny pack hoodie American Apparel twee. American\r\n");
      out.write("\t                  Apparel PBR listicle, salvia aesthetic occupy sustainable Neutra kogi. Organic synth Tumblr viral\r\n");
      out.write("\t                  plaid, shabby chic single-origin coffee Etsy 3 wolf moon slow-carb Schlitz roof party tousled squid\r\n");
      out.write("\t                  vinyl. Readymade next level literally trust fund. Distillery master cleanse migas, Vice sriracha\r\n");
      out.write("\t                  flannel chambray chia cronut.</p>\r\n");
      out.write("\t\r\n");
      out.write("\t                <p>Thanks,<br>Jane</p>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <!-- /.mailbox-read-message -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-body -->\r\n");
      out.write("\t            <div class=\"card-footer bg-white\">\r\n");
      out.write("\t              <ul class=\"mailbox-attachments d-flex align-items-stretch clearfix\">\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon\"><i class=\"far fa-file-pdf\"></i></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-paperclip\"></i> Sep2014-report.pdf</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>1,245 KB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon\"><i class=\"far fa-file-word\"></i></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-paperclip\"></i> App Description.docx</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>1,245 KB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon has-img\"><img src=\"../../dist/img/photo1.png\" alt=\"Attachment\"></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-camera\"></i> photo1.png</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>2.67 MB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                  <span class=\"mailbox-attachment-icon has-img\"><img src=\"../../dist/img/photo2.png\" alt=\"Attachment\"></span>\r\n");
      out.write("\t\r\n");
      out.write("\t                  <div class=\"mailbox-attachment-info\">\r\n");
      out.write("\t                    <a href=\"#\" class=\"mailbox-attachment-name\"><i class=\"fas fa-camera\"></i> photo2.png</a>\r\n");
      out.write("\t                        <span class=\"mailbox-attachment-size clearfix mt-1\">\r\n");
      out.write("\t                          <span>1.9 MB</span>\r\n");
      out.write("\t                          <a href=\"#\" class=\"btn btn-default btn-sm float-right\"><i class=\"fas fa-cloud-download-alt\"></i></a>\r\n");
      out.write("\t                        </span>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t              </ul>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-footer -->\r\n");
      out.write("\t            <div class=\"card-footer\">\r\n");
      out.write("\t              <div class=\"float-right\">\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-default\"><i class=\"fas fa-reply\"></i> Reply</button>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn btn-default\"><i class=\"fas fa-share\"></i> Forward</button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-default\"><i class=\"far fa-trash-alt\"></i> Delete</button>\r\n");
      out.write("\t              <button type=\"button\" class=\"btn btn-default\"><i class=\"fas fa-print\"></i> Print</button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- /.card-footer -->\r\n");
      out.write("          </div>       \t \r\n");
      out.write("       \t </div>\r\n");
      out.write("       \t</div><!-- .row -->\r\n");
      out.write("        \r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("    <!-- Control sidebar content goes here -->\r\n");
      out.write("    <div class=\"p-3\">\r\n");
      out.write("      <h5>Title</h5>\r\n");
      out.write("      <p>Sidebar content</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Footer -->\r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <!-- To the right -->\r\n");
      out.write("    <div class=\"float-right d-none d-sm-inline\">\r\n");
      out.write("      Anything you want\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Default to the left -->\r\n");
      out.write("    <strong>Copyright &copy; 2014-2019 <a href=\"https://adminlte.io\">AdminLTE.io</a>.</strong> All rights reserved.\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- REQUIRED SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/bootstrap/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
